name: Construir APK Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar tu código del repositorio
    - name: Chequear código
      uses: actions/checkout@v4

    # 2. Instalar Python 3.11 (Muy estable)
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Instalar Flutter (Canal 'stable' para evitar errores de confirmación)
    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    # 4. Instalar las librerías necesarias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Forzamos la instalación de flet por seguridad
        pip install flet

    # 5. Generar el APK (El comando mágico)
    - name: Construir APK
      run: |
        flet build apk --verbose

    # 6. Subir el archivo para que lo puedas descargar en "Artifacts"
    - name: Subir el APK generado
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/apk/app-release.apk
